name: ci

on:
  workflow_dispatch:
  workflow_call:

jobs:
  release:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/actions/prepare
      - name: Build + Test + Lint
        run: |
          bun run build
          bun run test
          bun run lint

      - name: Setup Node for npm publish
        uses: actions/setup-node@v4

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

